---
title: "RWorksheet_asenjo#4a"
author: "Samuel Asenjo"
date: "2024-10-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. 
```{r}
HouseHoldData <- data.frame (
  ShoeSize = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5,  11.0, 9.0, 13.0),
  
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
  
  Gender = c("F", "F", "F", "F","M", "F", "F", "F","M","F","M","F","M","M", "M", "M", "F", "F", "M", "F", "F","M", "M", "F","M","M", "M", "M")
)

HouseHoldData
```
a. The data shows that it has three columns namely, shoesize, height and, gender with 28 rows.


b. 
```{r}
s <- subset(HouseHoldData, Gender == "M" & ShoeSize&Height)
s

s2 <- subset(HouseHoldData, Gender == "F" & ShoeSize&Height)
s2
```
c. 
```{r}

sm <- mean(HouseHoldData$ShoeSize)
sm

hm <- mean(HouseHoldData$Height)
hm
```
d. No, because there are some respondents that is taller but has smaller shoe size that others who are shorter.

2. 
```{r}
months_vector <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July","December", "August", "August", "September", "November", "February", "April")

factor_months_vector <- factor(months_vector)

factor_months_vector
```
3. Yes, they are both useful because it shows the length, class, mode, and the number of repetitions of the character of two vectors.
```{r}
summary(months_vector)
summary(factor_months_vector)
```
4. 
```{r}
direction <- c("East", "West", "North")

frequency <- c(1, 4, 3)

factor_data <- direction
new_order_data <- factor(factor_data, levels = c("East", "West", "North"))

new_order_data



```


5. a.
```{r}
import_march <- read.table("import_march.csv", header = TRUE, sep =",")

```

b. 
```{r}
import_march
```
```{r}
 p <-as.integer( readline(prompt="Enter a number between 1 to 50: "))
if(!is.na(p) && p == 20){
  print("TRUE")
}else if (!is.na(p) && p >=1 && p <= 50){
   cat("Your number is", p)
}else{
print("The number selected is beyond the range of 1 to 50")}

```

7.
```{r}
p <- as.numeric(readline(prompt="Enter a price that is divisible by 50: "))

m <- function(p) {
b <- 0
if (!is.na(p) && p >= 1000) {
b <- b + p %/% 1000
p <- p %% 1000
}
4
if (!is.na(p) && p >= 500) {
b <- b + p %/% 500
p <- p %% 500
}
if (!is.na(p) && p >= 200) {
b <- b + p %/% 200
p <- p %% 200
}
if (!is.na(p) && p >= 100) {
b <- b + p %/% 100
p <- p %% 100
}
if (!is.na(p) && p >= 50) {
b <- b + p %/% 50
p <- p %% 50
}
return(b)
}
m(p)
```

8. a.
```{r}
g <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)

g
```

b. 
```{r}
a <- rowSums(g[,-1]) / (ncol(g) - 1)
if (any(a > 90)) {
n <- g$Name[a> 90]
s <- a [a > 90]
cat(paste(n, "'s average grade this semester is ", s, ".\n", sep = ""))
} else{
cat("There are no student that has an average grade over 90.\n")
}

```

c. 
```{r}
t <- colSums(g[,-1]) / nrow(g)
if (any(t < 80)) {
d <- which(t < 80)
cat(paste("The", d, "th test was difficult.\n"))
} else {
cat("All of the tests had average scores of 80 or above.\n")
}
```

d. 
```{r}
h <- apply(g[,-1], 1, function(x) sort(x, decreasing = TRUE)[1])
if (any(h > 90)) {
hn <- g$Name[h > 90]
hs <- h [h > 90]
cat(paste(hn, "'s highest grade this semester is ", hs, ".\n"))
} else {
cat("There are no student that has a highest grade exceeded 90.\n")
}

```

