---
title: "RWorksheet_Asenjo#1"
author: "Samuel Asenjo"
date: "2024-09-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.
a. There are 34 data points.

b.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41.)

length(age)
```

2. 
```{r}
library(MASS)
reciprocal_age <- 1/age

fractions(reciprocal_age)
```
   
3.
```{r}
new_age <- c(age, 0, age)

new_age
```
The values of age doubled in new age and has a zero between the object new_age.

4.
```{r}
sort(age)
```

5. 
```{r}
max(age)
min(age)
```

6. 
a. There are 12 data points.
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
2.3, 2.5, 2.3, 2.4, 2.7)

length(data)
```

7. 
The values of data was multiplied by 2.
```{r}
data2 <- data * 2

data2
```

8.1
```{r}
integer <- seq(1:100)
```

8.2

```{r}
numbers <-seq(20,60)

```
8.3
```{r}
Mean <- mean(numbers)
```
8.4
```{r}
number <- sum(51:91)

```
8.5
a. There are 143 data points from 8.1 to 8.4
b.
```{r}
int <- seq(1,1000)

length(integer) + length(numbers) + length(Mean) + length(number)
```
c. 
```{r}
 int <-10
max(int)
```

9. 
```{r}
Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
```

10. 
```{r}
backwards <- seq(100,1)
backwards
```
11.
```{r}
num <- 1:24
 m <- num[num %% 3 == 0 | num %% 5 == 0]
sum_multiples <- sum(m)
sum_multiples

```
a. There are 136 data points.
```{r}
length(backwards) + length(num) + length(m)  + length(sum_multiples)
```

12. 
```{r}
#x <- {0 + x + 5 + }
```
The output said error unexpected '}'

13. 
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75,
75, 77)

score[2]
score[3]
```
14. 
```{r}
a = c(1,2,NA,4,NA,6,7)

```
a.
```{r}
print(a,na.print="-999")
```
Using the na.print, all the NA in the vector a became -999.

15.
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
```
The output of the code is it prints the name and age I entered.
